In [2]:
import numpy as np

##datatypes and attributes

# numpy's main data type is nd array (n-dimensional array)

In [3]:
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2= np.array([[1,2,3],
              [4,5,6]])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
type(a3)

numpy.ndarray

shape of array a3= (2,3,3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a2.shape

(2, 3)

In [13]:
a1.shape

(3,)

In [14]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

no. of dimensions

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
# create a data frame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [17]:
df

0  1  2
0  1  2  3
1  4  5  6

In [18]:
df

0  1  2
0  1  2  3
1  4  5  6

##creating arrays

In [19]:
ones = np.ones((2,2),)

In [20]:
ones


array([[1., 1.],
       [1., 1.]])

In [21]:
ranged_array= np.arange(1,10,2)

In [22]:
ranged_array

array([1, 3, 5, 7, 9])

In [23]:
ranged_array= np.arange(0,10,2)
ranged_array

array([0, 2, 4, 6, 8])

In [24]:
random_arr= np.random.randint(1,10,size=(5,5))
random_arr

array([[9, 8, 1, 8, 6],
       [2, 3, 4, 6, 3],
       [7, 3, 4, 8, 7],
       [5, 1, 6, 5, 2],
       [7, 5, 7, 6, 4]])

In [25]:
random_arr.shape

(5, 5)

In [26]:
random_arr= np.random.randint(1,10,size=(2,5,5))
random_arr

array([[[5, 8, 5, 6, 4],
        [1, 1, 5, 5, 6],
        [4, 8, 9, 6, 9],
        [6, 1, 4, 4, 8],
        [9, 9, 4, 1, 5]],

       [[5, 5, 4, 2, 8],
        [9, 7, 3, 2, 3],
        [2, 7, 4, 8, 2],
        [4, 2, 7, 8, 2],
        [9, 3, 6, 1, 1]]])

In [27]:
random_arr.shape

(2, 5, 5)

#random seed- non random random numbers

In [28]:
np.random.seed(seed=0)
random_array_4= np.random.randint(10,size=(5,3))
random_array_4
#prevents number from changing/ reproducable random numbers (works no matter what your seed is)

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
np.random.seed(seed=999)
random_array_5= np.random.random((5,4))
random_array_5

array([[0.80342804, 0.5275223 , 0.11911147, 0.63968144],
       [0.09092526, 0.33222568, 0.42738095, 0.55438581],
       [0.62812652, 0.69739294, 0.78994969, 0.13189035],
       [0.34277045, 0.20155961, 0.70732423, 0.03339926],
       [0.90925004, 0.40516066, 0.76043547, 0.47375838]])

In [30]:
np.random.seed(seed=99)
random_array_5= np.random.random((5,4))
random_array_5

array([[0.67227856, 0.4880784 , 0.82549517, 0.03144639],
       [0.80804996, 0.56561742, 0.2976225 , 0.04669572],
       [0.9906274 , 0.00682573, 0.76979303, 0.7467671 ],
       [0.37743894, 0.49414745, 0.92894839, 0.39545404],
       [0.9739563 , 0.52441472, 0.09361309, 0.81330841]])

## viewing arrays and matrices

In [31]:
np.unique(random_array_4)
#np.unique(random_array_5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##viewing arrays and matrices

In [32]:
a1[0]

1

In [33]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [35]:
a4

array([[[[4, 9, 1, 9, 0],
         [5, 9, 3, 3, 6],
         [2, 5, 0, 5, 1],
         [2, 1, 9, 1, 3]],

        [[8, 8, 9, 2, 9],
         [8, 0, 7, 3, 2],
         [0, 6, 0, 2, 3],
         [2, 8, 3, 5, 5]],

        [[9, 4, 1, 4, 9],
         [7, 6, 5, 7, 5],
         [0, 3, 7, 9, 5],
         [7, 7, 8, 8, 0]]],


       [[[2, 3, 4, 0, 8],
         [0, 9, 0, 8, 4],
         [1, 0, 7, 9, 2],
         [7, 6, 1, 4, 2]],

        [[6, 8, 2, 2, 7],
         [2, 3, 2, 6, 1],
         [6, 3, 6, 7, 4],
         [4, 9, 9, 2, 7]],

        [[9, 5, 5, 1, 5],
         [0, 2, 7, 0, 6],
         [7, 2, 8, 6, 4],
         [2, 5, 0, 1, 7]]]])

In [36]:
a4[:,:,:,:1]

array([[[[4],
         [5],
         [2],
         [2]],

        [[8],
         [8],
         [0],
         [2]],

        [[9],
         [7],
         [0],
         [7]]],


       [[[2],
         [0],
         [1],
         [7]],

        [[6],
         [2],
         [6],
         [4]],

        [[9],
         [0],
         [7],
         [2]]]])

In [37]:
a4[:,:,:,:2]

array([[[[4, 9],
         [5, 9],
         [2, 5],
         [2, 1]],

        [[8, 8],
         [8, 0],
         [0, 6],
         [2, 8]],

        [[9, 4],
         [7, 6],
         [0, 3],
         [7, 7]]],


       [[[2, 3],
         [0, 9],
         [1, 0],
         [7, 6]],

        [[6, 8],
         [2, 3],
         [6, 3],
         [4, 9]],

        [[9, 5],
         [0, 2],
         [7, 2],
         [2, 5]]]])

## manipulating arrays & comparing arrays

#Arithmetic

In [38]:
a1

array([1, 2, 3])

In [39]:
ones= np.ones(3)
ones

array([1., 1., 1.])

In [40]:
a1+ones

array([2., 3., 4.])

In [41]:
a1-ones

array([0., 1., 2.])

In [42]:
a1 * ones

array([1., 2., 3.])

In [43]:
a1/ones

array([1., 2., 3.])

In [44]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a1 * a2 

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [46]:
#coding is fun

In [47]:
a2 * a3 [0,2,2]

array([[ 9, 18, 27],
       [36, 45, 54]])

In [48]:
a2//a1 #floor division removes decimals

array([[1, 1, 1],
       [4, 2, 2]])

In [49]:
a2 ** a1

array([[  1,   4,  27],
       [  4,  25, 216]])

In [50]:
np.square (a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [51]:
a1+ones

array([2., 3., 4.])

In [52]:
a1 %2 #modulo -> remainder thats left over

array([1, 0, 1], dtype=int32)

In [53]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [54]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

###Aggregation

In [55]:
listy_list= [1,2,3
            ]

In [56]:
type(listy_list)

list

In [57]:
sum(listy_list)

6

In [58]:
type(a1)


numpy.ndarray

In [59]:
a1

array([1, 2, 3])

In [60]:
sum(a1)


6

In [61]:
np.sum(a1)

6

In [88]:
np.random.seed(0)

mat1= np.random.randint (10,size=(3,5))
mat2= np.random.randint (10,size=(3,5))

mat3= mat1.transpose()
mat2
np.dot(mat3,mat2)

array([[ 96, 116, 128, 156,  41],
       [ 33,  27,  42,  57,  12],
       [ 67,  66,  85, 109,  23],
       [ 52,  39,  61,  82,  11],
       [ 65,  85,  84,  97,  23]])

In [91]:
mat1= np.random.randint (6,size=(3,5))
mat2= np.random.randint (6,size=(5,5))

#np.dot(mat1,mat2)
mat1.dot(mat2)

array([[27, 28, 43, 37, 39],
       [34, 37, 44, 23, 38],
       [51, 47, 65, 36, 43]])

In [86]:
mat3.shape

(5, 3)

##sorting arrays


In [103]:
random_array= np.random.randint(10,size=(3,5))
random_array

array([[8, 2, 3, 2, 0],
       [8, 8, 3, 8, 2],
       [8, 4, 3, 0, 4]])

In [104]:
np.sort(random_array)

array([[0, 2, 2, 3, 8],
       [2, 3, 8, 8, 8],
       [0, 3, 4, 4, 8]])

In [105]:
np.argsort(random_array)

array([[4, 1, 3, 2, 0],
       [4, 2, 0, 1, 3],
       [3, 2, 1, 4, 0]], dtype=int64)

##practical example- numpy in action

<img src="images/panda.png"/>

In [119]:
from matplotlib.image import imread

panda=imread("images/panda.png")
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [122]:
car=imread("images/car-photo.png")
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [124]:
dog=imread("images/dog-photo.png")
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)